// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Knew = require("knew");

function init(param) {
  var config = param[1];
  config.client = "pg";
  return Knew(config);
}

function Make(funarg) {
  var knex = function (name) {
    return funarg[/* client */0](name);
  };
  return [
          knex,
          (function (prim, prim$1) {
              return prim$1.where(prim);
            })
        ];
}

exports.init = init;
exports.Make = Make;
/* knew Not a pure module */
